no var

diff --git a/.github/workflows/process-pre-release.yml b/.github/workflows/process-pre-release.yml
--- a/.github/workflows/process-pre-release.yml
+++ b/.github/workflows/process-pre-release.yml
@@ -5,9 +5,6 @@ on:
   release:
     types: [ prereleased ]
 
-env:
-  TAG: ${{ github.event.release.tag_name }}
-
 
 jobs:
   info:
@@ -16,5 +13,5 @@ jobs:
       - name: Print Info
         run: |
           echo 'Pre-release triggered me!'
-          [[ "${{ TAG }}" =~ ^[0-9]+\.[0-9]+\.[0-9]+-beta.[0-9]+$ ]] || echo "Invalid tag"; exit 1;
+          [[ "${{ github.event.release.tag_name }}" =~ ^[0-9]+\.[0-9]+\.[0-9]+-beta.[0-9]+$ ]] || echo "Invalid tag"; exit 1;
           echo "All is good :)"
